### ISSUE TITLE
运行不起来

### ISSUE THREAD

**Issue by PeterXiaoWang** [Runpop/RxZhihuPager#2]
This version of Android Studio is incompatible with the Gradle Plugin used. Try disabling Instant Run.
这是啥情况

**Comment by Diffey** [comment]
如上描述，你的Android Studio版本低。解决办法：升级Android Studio 或者禁用Instant Run

**Comment by PeterXiaoWang** [comment]
![image](https://cloud.githubusercontent.com/assets/8265748/13240886/4cba615a-da21-11e5-81d4-4142ba0a8ccc.png)
是这样禁用吗

**Comment by Diffey** [comment]
是的，现在可以了么

**Comment by PeterXiaoWang** [comment]
还是不行，是因为低版本的AS不支持一些插件吗？

**Comment by Diffey** [comment]
那你更新一下AS吧
